const discos = [
  {
    id: 17,
    imagen: "Zeitreise.jpg",
    titulo: "Zeitreise",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "EP",
    anio: 2019,
    copias: 500,
    precio: 800,
  },
  {
    id: 16,
    imagen: "Testimonium.jpg",
    titulo: "Testimonium",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "LP",
    anio: 2017,
    copias: 450,
    precio: 800,
  },
  {
    id: 15,
    imagen: "Hoffnung.jpg",
    titulo: "Hoffnung",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "LP",
    anio: 2015,
    copias: 400,
    precio: 750,
  },
  {
    id: 14,
    imagen: "MorningGlory.jpg",
    titulo: "Morning Glory",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "EP",
    anio: 2013,
    copias: 400,
    precio: 750,
  },
  {
    id: 13,
    imagen: "Revolution.jpg",
    titulo: "Revolution",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "LP",
    anio: 2012,
    copias: 350,
    precio: 700,
  },
  {
    id: 12,
    imagen: "Schattenspiel.jpg",
    titulo: "Schattenspiel",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "EP",
    anio: 2010,
    copias: 300,
    precio: 650,
  },
  {
    id: 11,
    imagen: "ILostMystar.jpg",
    titulo: "I Lost My star",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "EP",
    anio: 2009,
    copias: 300,
    precio: 650,
  },
  {
    id: 10,
    imagen: "Lichtjhare.jpg",
    titulo: "Lichtjhare",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "EP",
    anio: 2007,
    copias: 250,
    precio: 600,
  },
  {
    id: 9,
    imagen: "Lichtgestalten.jpg",
    titulo: "Lichtgestalten",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "EP",
    anio: 2006,
    copias: 250,
    precio: 600,
  },
  {
    id: 8,
    imagen: "Lichgestalt.jpg",
    titulo: "Lichtgestalt",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "LP",
    anio: 2005,
    copias: 200,
    precio: 550,
  },
  {
    id: 7,
    imagen: "Echos.jpg",
    titulo: "Echos",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "LP",
    anio: 2003,
    copias: 150,
    precio: 500,
  },
  {
    id: 6,
    imagen: "Elodia.jpg",
    titulo: "Elodia",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "LP",
    anio: 1999,
    copias: 150,
    precio: 500,
  },
  {
    id: 5,
    imagen: "Live.jpg",
    titulo: "Live",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "EP",
    anio: 1998,
    copias: 100,
    precio: 400,
  },
  {
    id: 4,
    imagen: "Stille.jpg",
    titulo: "Stille",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "LP",
    anio: 1997,
    copias: 99,
    precio: 300,
  },
  {
    id: 3,
    imagen: "AllesLuge.jpg",
    titulo: "Alles Lugue",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "EP",
    anio: 1993,
    copias: 50,
    precio: 200,
  },
  {
    id: 2,
    imagen: "Einsamkeit.jpg",
    titulo: "Einsamkeit",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "LP",
    anio: 1992,
    copias: 50,
    precio: 200,
  },
  {
    id: 1,
    imagen: "Angst.jpg",
    titulo: "Angst",
    artista: "Lacrimosa",
    discografica: "Hall of Sermon",
    categoria: "LP",
    anio: 1991,
    copias: 1,
    precio: 100,
  },
];

export default discos;
